#!/bin/bash

# Script Name:                        arrays.sh
# Author:                             Jasmine Pressley
# Date of latest revision:            10/26/2023
# Purpose:                            Ops Challenge: Class 04

# Declaration of variables
folders=("dir1" "dir2" "dir3")

# Declaration of functions
createfile() {
mkdir ${folders[@]}
touch ${folders[0]}/textfile.txt
touch ${folders[1]}/textfile.txt
touch ${folders[2]}/textfile.txt
touch ${folders[3]}/textfile.txt
}

#main

createfile Jasmine

# End
